server {
    
}



# example of config file without CGI

# server {    
#     listen 8080;
#     server_name myserver; "myserv" + fd

#     root /var/www/html;

#     index index.html;

#     location / {
#         autoindex off;
#     }

#     location /images {
#         root /var/www/assets;
#     }

#     error_page 404 /errors/404.html;
# }
