server {
    listen 8080;

	error_page 404 ./www/error_pages/404.html;
	error_page 405 ./www/error_pages/405.html;
	error_page 413 ./www/error_pages/413.html;
	error_page 500 ./www/error_pages/500.html;

	client_max_body_size 10M;

	location / {
		root ./www;
		index index.html;
		allowed_methods GET POST DELETE;
	}

	location /upload {
		root ./www/uploads;
		allowed_methods GET POST;
		upload_path ./www/uploads;
		client_max_body_size 200M;
	}

	location /autoin {
	root ./src;
	autoindex on;
	allowed_methods GET;
	}

	location /redir {
		return 302 /autoin;
	}

	location /redir-google {
		return 302 http://google.com;
	}


	location /cgi-bin/py {
		root ./www/py-scripts/;
		cgi_extension .py;
		cgi_path ./www/py-scripts/.venv/bin/python3;

		allowed_methods GET POST;
	}

	location /cgi-bin/sh {
		root ./www/sh-scripts/;
		cgi_extension .sh;
		cgi_path /usr/bin/bash;

		allowed_methods GET POST;
	}

	location /cgi-bin/pl {
		root ./www/pl-scripts/;
		cgi_extension .pl;
		cgi_path /usr/bin/perl;

		allowed_methods GET POST;
	}


}

server {
    listen 127.0.0.1:8081;

	client_max_body_size 9M;

	location / {
		root /home/nmagomad/www;
		index index.html;
		allowed_methods GET POST DELETE;

	}
}


# server {
#     listen 8080;
#
# 	client_max_body_size 9M;
#
# 	location / {
# 	root /home/nmagomad/www;
# 		index index.html;
# 		allowed_methods GET POST DELETE;
# 	}
# }
